services:
  postgres:
    container_name: pg15alpine
    image: postgres:15-alpine
    restart: always
    env_file: .env
    networks:
      - pg
    ports:
      - 54301:54321
    volumes:
      - var-lib-postgresql-data:/var/lib/postgresql/data/
      # - ./bind/var-lib-postgresql:/var/lib/postgresql/data/
      - ./bind/etc-pgdump:/etc/pgdump/
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file: .env
    networks:
      - nginx
      - pg
    ports:
      - 5050:80
      - 5051:443
    volumes:
      - var-lib-pgadmin:/var/lib/pgadmin
      # - ./bind/var-lib-pgadmin:/var/lib/pgadmin
      # - ./bind/pgadmin4:/pgadmin4
      # - ./bind/pgadmin4/servers.json:/pgadmin4/servers.json
      # - ./path/to/certificate.cert:/certs/server.cert
      # - ./path/to/certificate.key:/certs/server.key
    depends_on:
      - postgres

networks:
  pg:
    external: true
  nginx:
    external: true

volumes:
  var-lib-postgresql-data:
    # external: true
  var-lib-pgadmin:
    # external: true
