services:
  pg15alpine:
    container_name: pg15alpine
    image: postgres:15-alpine
    restart: always
    env_file: .env
    networks:
      - host
    ports:
      - 54301:54321
    volumes:
      - ./bind/var-lib-postgresql:/var/lib/postgresql/data/
      # - vol_pg15_data:/var/lib/postgresql/data/
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    env_file: .env
    networks:
      - host
    ports:
      - 5050:80
      - 443:443
    volumes:
      - ./bind/var-lib-pgadmin:/var/lib/pgadmin
      # - ./bind/pgadmin4:/pgadmin4
      # - ./path/to/certificate.cert:/certs/server.cert
      # - ./path/to/certificate.key:/certs/server.key
      - ./bind/pgadmin4/servers.json:/pgadmin4/servers.json
    depends_on:
      - pg15alpine
