services:
  pg15alpine:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - net_pg
    ports:
      - '54321:54321'
    volumes:
      - vol_pg15_data:/var/lib/postgresql/data/pgdata
      - type: bind
        source: ./postgresql.conf
        target: /etc/postgresql/postgresql.conf

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    networks:
      - net_pg
    ports:
      - '5050:80'
    depends_on:
      - pg15alpine

networks:
  net_pg:
    external: true

volumes:
  vol_pg15_data:
    external: true
